### ISSUE TITLE
handle function types in the same way as function pointer types are handled

### ISSUE THREAD

**Issue by mraleph** [dart-lang/ffigen#102]
This is a valid C code:

```cpp
typedef int foo_t(int);

int bar(foo_t x) {
   return x(10); 
}

int foo(int y) { return y + 1; }

int main() {
  bar(foo);
}
```

Notice that `foo_t` declares function type, rather than function pointer type. 

`ffigen` currently emits `NativeFunction<...>` as a parameter to `bar` - which is not legal. It should be `Pointer<NativeFunction<...>>` instead. 

Discovered this issue when generating bindings for [replxx](https://github.com/AmokHuginnsson/replxx) library.

Side note, however this:

```cpp
struct S {
  foo_t foo;
};
```

is valid in C++ but not in C. But that should not concern us much.

**Comment by mannprerak2** [comment]
This seems like a shorthand built into C.

This issue, however, should not happen in case of **nested types**
E.g - Bindings for this
```C
typedef int foo_t(int);
typedef int (*foo_t2)(foo_t x); // Not defined as a pointer.

void bar(foo_t2 x);
```
& this
```C
typedef int foo_t(int);
typedef int (*foo_t2)(foo_t *x); // specified as a pointer.

void bar(foo_t2 x);
```
Are exactly same
```dart
void bar(
    ffi.Pointer<ffi.NativeFunction<foo_t2>> x,
  ) {
    _bar ??= _dylib.lookupFunction<_c_bar, _dart_bar>('bar');
    return _bar(
      x,
    );
  }
...

typedef foo_t2 = ffi.Int32 Function(
  ffi.Pointer<ffi.NativeFunction<_typedefC_1>>,    // Will be a pointer to NativeFunc in either case.
);
```
`foo_t x` is automatically converted to `foo_t *x` (to a function pointer) in nested types because the type for `foo_t2` is resolved by `clang_getCanonicalType_wrap` which removes all sugar and performs the conversion.
