### ISSUE TITLE
Dart enum

### ISSUE THREAD

**Issue by listepo** [dart-lang/ffigen#114]
@mannprerak2 @dcharkes can you add the generation of dart enums instead of abstract classes where possible?

**Comment by mannprerak2** [comment]
C enum constants can be negative, have the same values, skip some integer values between 2 enum constants values. On the other hand, Dart enums are not as flexible as C enums.

For example, something like this cannot be represented in a dart enum.
```C
enum hello
{
    a = 1,
    b = -1,
    c, // 0
    d, // 1 (same as a)
    f = 10,
    g, // 11
};
```

Now, we may be able to cover a few use cases, but in order to keep things consistent, it's best not to use them.

However, it may be possible to make the generated class more useful instead. Perhaps something similar to how `Enum Class` works from package:[build_value](https://pub.dev/packages/built_value).

**Comment by listepo** [comment]
I understand, I hope in the future enums for dart will become more flexible

**Comment by Sunbreak** [comment]
Any progress?
