### ISSUE TITLE
make removal of all struct fields in presense of bit fields optional

### ISSUE THREAD

**Issue by maks** [dart-lang/ffigen#141]
Currently (due to #85) all struct fields are removed when bit fields are detected.

But for some cases, eg `fuse_operations` in https://github.com/libfuse/libfuse/blob/master/include/fuse.h#L299 
where its a huge struct with just a few bitfields, it would be nice for at least most of the struct to still be generated and leave me to manually add in the bitfields. I know its not ideal editing the generated file but it's much better than needing to write that whole struct by hand.

Currently I'm basically working around this by editing the header file to temporarily comment out the bitfields in the struct.

So perhaps there could be a config setting like `allow_partial_structs_despite_bitfields` at least until bitfield support is available?

**Comment by mannprerak2** [comment]
@maks The reason we do not generate partial structs is due to alignment and size issues. If you simply remove some field from between, the rest of the structure will not work correctly, since the alignment and size of the struct will get changed.

That's why keeping partial structs is dangerous since that can make the bindings not work. It may cause a segmentation fault, but it's also possible to get some garbage values that will be extremely hard to debug.

Now you could do some hacks to work with bitfields, See https://github.com/dart-lang/sdk/issues/38954#issuecomment-546891847. But you need to be sure about this approach as it is very likely that this will not be platform agnostic.

**Comment by mannprerak2** [comment]
@maks I noticed you are commenting out the bit fields [here](https://github.com/maks/dart_fuse/commit/90e8a61538785ba5916677eafa3164ada7814cf6).

I can recommend a better way, you can simply enclose the bitfield definitions inside a `#ifndef --- #endif` and then define macros to exclude it using `compiler-opts`.

E.g -
```c
struct A
{
    int a, b, c;

    #ifndef NO_BITFIELD
      int bf1 : 3;
      int bf2 : 5;
    #endif

};
```

The generate struct will be empty due to bitfields, but if you add this in your config
```yaml
ffigen:
  ...
  compiler-opts: "-D NO_BITFIELD"     # define the macro
```

Then the bitfields will not be considered and you generate the struct you need.

**Comment by maks** [comment]
@mannprerak2 that's a great tip, thank you! That will do exactly what I want! And really achieves the result I was asking for with the option flag 👍
