### ISSUE TITLE
Unavailable inline C function

### ISSUE THREAD

**Issue by Sunbreak** [dart-lang/ffigen#146]
Ref: https://github.com/woodemi/libusb.dart/issues/10

Inline C function

```c
static inline uint16_t libusb_cpu_to_le16(const uint16_t x)
```

generates Dart function

```dart
int libusb_cpu_to_le16(
  int x,
)
```

which is unavailable within dynamic library

---

Could we skip `inline` functions or generate some inline implementations?

**Comment by dcharkes** [comment]
We should skip them. (Generating an implementation for an arbitrary function would be very involved.)

**Comment by Sunbreak** [comment]
Solved via `ffi: ^2.0.1` since https://github.com/woodemi/libusb.dart/releases/tag/0.3.23-nullsafety.0

**Comment by Sunbreak** [comment]
BTW, why `--enable-experiment: non-nullable` is needed in [analysis_options.yaml](https://github.com/woodemi/libusb.dart/blob/0.3.23-nullsafety.0/analysis_options.yaml), or`dart migrate` fails with `This requires the 'non-nullable' language feature to be enabled.`

On the other hand, running example via `dart` doesn't require `--enable-experiment=non-nullable`

[`analyzer: 1.0.0`](https://pub.dev/packages/analyzer/versions/1.0.0) has `nullsafety` support already

Ref: https://stackoverflow.com/questions/57598838/non-nullable-by-default-how-to-enable-the-experiment

**Comment by mannprerak2** [comment]
> why --enable-experiment: non-nullable is needed in analysis_options.yaml, or dart migrate fails with This requires the 'non-nullable' language feature to be enabled.

I am not sure what's exactly happening, can you give some more details?

My guess is that you might be running examples from the `master` branch. Please try out the `dart-dev` branch (it depends sdk version `2.12.0-259.beta`. The examples in `master` branch currently run in unsound null safety. so you don't need the flag when running those.

The analyzer shouldn't complain about enabling the flag, since it has been enabled by default on `2.12.0-259.beta`. Maybe your IDE is using an older version of dart SDK?

**Comment by Sunbreak** [comment]
Thanks for response. I'd like to file another issue in https://github.com/dart-lang/sdk
