### ISSUE TITLE
[Windows] long is converted as Uint64

### ISSUE THREAD

**Issue by Sunbreak** [dart-lang/ffigen#160]
# Reproduce

```c
// C
typedef struct _GUID {
    unsigned long  Data1;
    unsigned short Data2;
    unsigned short Data3;
    unsigned char  Data4[ 8 ];
} GUID;
```

```dart
// Dart
class GUID extends ffi.Struct {
  @ffi.Uint64()
  external int Data1;

  @ffi.Uint16()
  external int Data2;

  @ffi.Uint16()
  external int Data3;

  @ffi.Uint8()
  external int _unique_Data4_item_0;
  @ffi.Uint8()
  external int _unique_Data4_item_1;
  @ffi.Uint8()
  external int _unique_Data4_item_2;
  @ffi.Uint8()
  external int _unique_Data4_item_3;
  @ffi.Uint8()
  external int _unique_Data4_item_4;
  @ffi.Uint8()
  external int _unique_Data4_item_5;
  @ffi.Uint8()
  external int _unique_Data4_item_6;
  @ffi.Uint8()
  external int _unique_Data4_item_7;
// ...
}
```

# Expected

Official doc: https://docs.microsoft.com/en-us/cpp/cpp/data-type-ranges

Dart package `win32` implementation: https://github.com/timsneath/win32/blob/main/lib/src/structs.dart#L1830

```dart
class GUID extends Struct {
  @Uint32()
  external int Data1;
  @Uint16()
  external int Data2;
  @Uint16()
  external int Data3;
  @Uint64()
  external int Data4;
// ...
}
```

**Comment by mannprerak2** [comment]
`long` could be implemented as 4 or 8 bytes, the definition for long is that it should atleast be 4 bytes.

By default we choose 8 bytes for representing `long`. Since there is no way, as of now, to generate platform independent bindings (See #7)

However, you can override this value using the `size-map` property (See [readme.md](https://github.com/dart-lang/ffigen/blob/master/README.md#configurations))

Add this to your config -
```yaml
size-map:
  unsigned long: 4
  long: 4
```

**Comment by Sunbreak** [comment]
Solved. Thanks a lot
