### ISSUE TITLE
packed structs

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/ffigen#204]
`2.13.0-211.6.beta` has support for packed structs (https://github.com/dart-lang/sdk/issues/38158).

Can we detect with clang a struct is packed? and add the right annotation to it?

**Comment by mannprerak2** [comment]
We can get the alignment of a struct using this function
```C
long long clang_Type_getAlignOf(CXType T);
```
and use it for annotation`@Packed(<align-value>)`.

Do we need any other config for this?

**Comment by dcharkes** [comment]
> Will this be platform-independent though? Can this value be different on different platforms?

I don't think always emitting @Packed aways is platform independent.

Ideally, we would only emit `@Packed(1, 2, 4, 8, or 16)` if packing is used on the struct. For example https://github.com/dart-lang/sdk/blob/master/runtime/bin/ffi_test/ffi_test_functions_generated.cc#L470, but not the structs before that one in the file.

If we can't detect if packing is used from clang, then we might want to use a configuration option to specify packing instead.

**Comment by mannprerak2** [comment]
We can only use the `align` value returned by `clang_Type_getAlignOf` if the struct was packed, otherwise the generated code is not platform-independant.

There are 2 ways to specify how a struct is packed in C -
1. Using `__attribute__((__packed__))` or`__attribute__((__packed__, aligned(X)))` on a struct -> This can be easily detected with libclang.
2. Using `#pragma pack(...)` -> Unfortunately libclang **doesn't** expose this (See https://github.com/rust-lang/rust-bindgen/issues/537#issuecomment-335898418)
    1. Workaround -> We can check if any of the members of the struct has an `align` value greater than the align value of the parent struct, and if it is then we know for sure that the struct was packed.
3. There's also `__attribute__((aligned(X)))` which sets the minimum alignment for a struct, (i.e alignment could be more if a member has a value greater than X -> For this we can pack if the maximum align value of any child is less than the align value of parent struct.

I think this covers everything, so there is no need for adding a config to specify the packing of a struct explicitly.

**Comment by dcharkes** [comment]
P.S. A Good stresstest would be to compare the generated bindings with the ones that @timsneath has been generating from the win32 meta-data repository in https://github.com/timsneath/win32. (I'm sure the metadata repository has more information than the C header files, so ffigen might not be as precise, but it would be cool to see if we end up with the same generated bindings.)

**Comment by mannprerak2** [comment]
We will have to also provide users a way to specify the packing via the config since -
1. It's possible to pack structs via some command-line argument when compiling a shared library.
2. To work around some missing edge cases, plus it's better to have the flexibility.

The config can be something like this -
```yaml
structs:
  pack:
    'ShortStruct': 2 # value can be [0, 1, 2, 4, 8 ,16]. 0 means no packing is applied.
    '.*': 1
    'NotPackedStruct': 0 
```

This allows users to _override_ the generated values, so this config will only be needed if the generated `Packed` annotation is incorrect.

**Comment by dcharkes** [comment]
Maybe use `none` instead of `0`.

And yes an option for `.*` (or other regex). Great thinking! 🚀

**Comment by timsneath** [comment]
In my Win32 code, [structs.g.dart](https://github.com/timsneath/win32/blob/main/lib/src/structs.g.dart) represents all the structs I'm able to generate automatically today; [structs.dart](https://github.com/timsneath/win32/blob/main/lib/src/structs.dart) represents all the structs I still have to generate manually (mostly because of the lack of union support).

**Comment by mannprerak2** [comment]
Thanks @timsneath I'll take a look.
