### ISSUE TITLE
Add an option to use leaf functions for C functions that don't accept callbacks

### ISSUE THREAD

**Issue by Keithcat1** [dart-lang/ffigen#251]
I was reading [https://gist.github.com/mraleph/2582b57737711da40262fad71215d62e](https://gist.github.com/mraleph/2582b57737711da40262fad71215d62e) and it mentioned that calling a leaf function(NativeFunction.asFunction(leaf: true)) is faster than calling a non-leaf function and might at some point allow the C function to receive pointers into Dart memory such as typed data without having to allocate temporary C memory.
There should be an option for making leaf functions if they don't have any callback parameters. It should probably not be the default because the C function might still have a Dart function pointer saved somewhere.

**Comment by dcharkes** [comment]
We probably would like to have a glob-like-filter for this just like we use filters for all the other config features so that users can pick and choose.

@Keithcat1 What about having a filter with `*` (generate leaf-functions for all) and then manually ignoring opting out for the ones that you'd not want (because of callbacks):

```yaml
functions:
  leaf:
    include:
      - '.*'
    exclude:
      - 'my_callback1'
      - 'my_callback2'
```

Or do you have a use case in which that approach would be too cumbersome?

**Comment by Keithcat1** [comment]
No, sounds good.
