### ISSUE TITLE
ObjC: Strings not correctly created if they contain NUL

### ISSUE THREAD

**Issue by brianquinlan** [dart-lang/ffigen#329]
```dart
        final s = 'Embedded\u0000Null';
        final ns1 = NSString(lib, s);
        expect(ns1.toString(), s);
```

```
  Expected: 'Embedded\x00Null'
    Actual: 'Embedded'
```

I tried to fix this with:
```dart
  void _addNSStringMethods() {
    addMethodIfMissing(ObjCMethod(
      originalName: 'initWithCharacters:length:',
      kind: ObjCMethodKind.method,
      isClass: false,
      returnType: this,
      params_: [
        ObjCMethodParam(PointerType(unsignedShortType), 'characters'),
        ObjCMethodParam(unsignedIntType, 'length'),
      ],
    ));
    addMethodIfMissing(ObjCMethod(
      originalName: 'UTF8String',
      kind: ObjCMethodKind.method,
      isClass: false,
      returnType: PointerType(charType),
      params_: [],
    ));
  }

  factory NSString(StringTestObjCLibrary _lib, String str) {
    print("$str ${str.length}");
    final cstr = str.toNativeUtf16();
    print("$cstr ${cstr.length}");
    final nsstr =
        alloc(_lib).initWithCharacters_length(cstr.cast(), str.length);
    pkg_ffi.calloc.free(cstr);
    return nsstr;
  }
```

But the string seems to be truncated somewhere:
```
EmbeddedNull 13
Pointer<Utf16>: address=0x600001f05ca0 8
```

**Comment by liamappelbe** [comment]
After reading through the Objective C and FFI documentation, the only way to do this correctly is to use UTF-16 as the interop, rather than UTF-8. This should be faster too, since both Objective C and Dart use UTF-16 internally in their strings, so this should save a couple of conversions.

Dart String -> `toNativeUtf16` -> `stringWithCharacters:length:` -> ObjC NSString
ObjC NSString -> `dataUsingEncoding:allowLossyConversion:` -> `toDartString(length:)` -> Dart String

Unfortunately, this is non-trivial, because `dataUsingEncoding` returns an `NSData`, rather than a direct pointer. So to add the method to `NSString` using `addMethodIfMissing`, we need the `ObjCInterface` for `NSData`. We don't have any infrastructure at the moment to lookup interfaces by name, so that needs to be built. We should probably also promote `NSData` to an ergonomically wrapped class at the same time, like we do for `NSString`.
