### ISSUE TITLE
Migrate existing C++ library to dart FFI

### ISSUE THREAD

**Issue by hawkkiller** [dart-lang/ffigen#406]
So, I have a big C++ library. Is there any possibility to use its code without refactoring into C? Because it uses the c++ types everywhere and extern C will not work there. Also, it has about 200 cpp files and an entry-point with all functios wrappers that the library provide.

**Comment by dcharkes** [comment]
Unfortunately, C++ does not have a stable ABI. This means it is undefined what the register/stack layout is when one calls functions in a `.dll`, `.so`, `.dylib`. It might work if you happen to have compiled the caller with the same compiler, but it is not guaranteed to work like it is for C. We cannot know in Dart with which compiler you compiled your C++ code. C has defined the Application Binary Interface which every compiler adheres to, so that we can know how to call it.

For more info see https://github.com/dart-lang/sdk/issues/38788.

**Comment by hawkkiller** [comment]
So, do I need to create a wrapper for each function?

**Comment by dcharkes** [comment]
Yes, that is the only known workaround if you already have a large C++ codebase.

If you're starting from scratch you could opt to use IDL, and generate bindings for multiple languages from that, but I don't have experience retrofitting IDL on top of an existing codebase.

**Comment by TimWhiting** [comment]
This might help? I haven't tried it, but I'm also interested in wrapping c++ libraries for dart.

https://cpp2c.webs.com/

**Comment by mannprerak2** [comment]
@dcharkes should we close this? since it can't be solved directly with ffigen (a C wrapper is the way to go)

**Comment by hawkkiller** [comment]
@mannprerak2 Closing this issue, thanks for reminder. Everything was pretty clear and I have successfully created the binding to the wrapper.
