### ISSUE TITLE
EXC_BAD_ACCESS error when using ffi with ffigen to access HealthKit on iOS

### ISSUE THREAD

**Issue by jeanantoine** [dart-lang/ffigen#574]
Hello,

I'm trying to use ffi with ffigen to access HealthKit on iOS. I've included my `main.dart` and `pubspec.yaml` files in this gist: https://gist.github.com/jeanantoine/28cc7ff1e9d08fe360e2a720b4be657c

When I run my code, I get the following runtime error:

```
flutter: #### before executeQuery_
    thread #3, queue = ‘com.apple.HealthKit.HKHealthStore.client.0x282203670’, stop reason = EXC_BAD_ACCESS (code=1, address=0x10c8c8000) frame #0: 0x000000010c8c8000 error: memory read failed for 0x10c8c8000 Target 0: (Runner) stopped.
```
Can anyone help me understand what might be causing this error and how I can fix it?

Thank you!

**Comment by dcharkes** [comment]
cc @liamappelbe

**Comment by liamappelbe** [comment]
The crash is probably because your `resultsHandler` is being called by HealthKit on one of its worker threads. At the moment, callbacks into Dart only work if they're called on the same thread that created the callback.

We're working on fixing it so that callbacks can be called from an arbitrary thread. You can follow the progress of that here: https://github.com/dart-lang/sdk/issues/37022

If you can't wait for that feature to land, the workaround at the moment is to write your results handler in objective C, and then forward the result to the target isolate over a [Dart_Port](https://api.dart.dev/stable/3.0.0/dart-ffi/NativePort.html). This is how [package:cupertino_http](https://github.com/dart-lang/http/blob/master/pkgs/cupertino_http/src/CUPHTTPClientDelegate.m) works.

**Comment by jeanantoine** [comment]
@liamappelbe :
thank you for your response. I have a working code with method channel for accessing HealthKit in Swift. I wanted to write the code in Dart only.

**Comment by liamappelbe** [comment]
`ObjCBlock.listener` has landed: https://github.com/dart-lang/ffigen/pull/601
