### ISSUE TITLE
[Question] typedef struct

### ISSUE THREAD

**Issue by listepo** [dart-lang/ffigen#73]
I'm not a big expert in C and Dart. I have a couple of questions
I have a sample:
from
```c
typedef struct _PQconninfoOption
{
	char	   *keyword;		/* The keyword of the option			*/
	char	   *envvar;			/* Fallback environment variable name	*/
	char	   *compiled;		/* Fallback compiled in default value	*/
	char	   *val;			/* Option's current value, or NULL		 */
	char	   *label;			/* Label for field in connect dialog	*/
	char	   *dispchar;		/* Indicates how to display this field in a
								 * connect dialog. Values are: "" Display
								 * entered value as is "*" Password field -
								 * hide value "D"  Debug option - don't show
								 * by default */
	int			dispsize;		/* Field size in characters for dialog	*/
} PQconninfoOption;

/* get info about connection options known to PQconnectdb */
extern PQconninfoOption *PQconndefaults(void);
```

to 

```dart
/// AUTO GENERATED FILE, DO NOT EDIT.
///
/// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Bindings to Postgresql
class Postgresql {
  /// Holds the Dynamic library.
  final ffi.DynamicLibrary _dylib;

  /// The symbols are looked up in [dynamicLibrary].
  Postgresql(ffi.DynamicLibrary dynamicLibrary) : _dylib = dynamicLibrary;

  ffi.Pointer<_PQconninfoOption> PQconndefaults() {
    _PQconndefaults ??=
        _dylib.lookupFunction<_c_PQconndefaults, _dart_PQconndefaults>(
            'PQconndefaults');
    return _PQconndefaults();
  }

  _dart_PQconndefaults _PQconndefaults;
}

class _PQconninfoOption extends ffi.Struct {
  ffi.Pointer<ffi.Int8> keyword;

  ffi.Pointer<ffi.Int8> envvar;

  ffi.Pointer<ffi.Int8> compiled;

  ffi.Pointer<ffi.Int8> val;

  ffi.Pointer<ffi.Int8> label;

  ffi.Pointer<ffi.Int8> dispchar;

  @ffi.Int32()
  int dispsize;
}

class PQconninfoOption extends ffi.Struct {
  ffi.Pointer<ffi.Int8> keyword;

  ffi.Pointer<ffi.Int8> envvar;

  ffi.Pointer<ffi.Int8> compiled;

  ffi.Pointer<ffi.Int8> val;

  ffi.Pointer<ffi.Int8> label;

  ffi.Pointer<ffi.Int8> dispchar;

  @ffi.Int32()
  int dispsize;
}

typedef _c_PQconndefaults = ffi.Pointer<_PQconninfoOption> Function();

typedef _dart_PQconndefaults = ffi.Pointer<_PQconninfoOption> Function();

```

This is the correct result?

`WARNING : Generated declaration '_PQconninfoOption' start's with '_' and therefore will be private.`
Should we get this warning here?

Should we have two identical `_PQconninfoOption` and `PQconninfoOption`?
Why do we use `_PQconninfoOption` instead of `PQconninfoOption`?

**Comment by dcharkes** [comment]
There are two identifiers defined in C: `_PQconninfoOption` in the struct namespace and `PQconninfoOption` in the global namespace, see https://stackoverflow.com/a/1675446/8136619.

> Should we have two identical _PQconninfoOption and PQconninfoOption?

No, probably not - I think we should prefer the name in the global namespace if there are two names.

**Comment by mannprerak2** [comment]
There are 2 things involved here 
1. The function using the inner struct instead of outer typedef as struct.
2. Multiple structs being generated.

For 2, the issue is that libclang doesn't tell us if a struct is enclosed in a typedef.
Suppose we have this
```C
typedef struct _A{
  int a;
} A;
```
It seems like there is no way in libclang to check if `struct _A` is inside a typedef or a separate declaration while parsing it.

**And there could also be multiple typedefs referring to the same struct** which will all actually be same but have different names and hence will be generated repeatedly.

@dcharkes I am not sure what the best solution can be, it would have been simple if dart also had typealias which we could then use easily. But maybe we should use the inner struct names(if available) and only use the typedef name incase inner struct is Anonymous.

Also see #79

**Comment by mannprerak2** [comment]
@listepo this has been fixed in the master branch, it hasn't been published yet and might be worked upon again, so you may try it via a git dependency for now.
